name: Issue moderator with commands
description: Automatically close or lock issues based on commands.
author: tachiyomiorg
branding:
  icon: alert-circle
  color: red
inputs:
  repo-token:
    required: true
    description: GitHub token
  edit-title-command:
    required: false
    default: Edit title to
    description: Command to edit the title of an issue
  lock-command:
    required: false
    default: Lock this issue
    description: Command to lock an issue
  duplicate-command:
    required: false
    default: 'Duplicate of #'
    description: Command to close a duplicate issue
  duplicate-check-enabled:
    required: false
    description: >
      Control if the action should search for duplicate URLs in opened issues.
      Set it to 'true' if you want to enable.
  duplicate-check-label:
    required: false
    description: >
      The label of the opened issues that will be check.
      It's required if you have enabled the duplicate finder.
  duplicate-check-comment:
    required: false
    description: >
      The body of the comment when an issue is detected to be a duplicate.
    default: |
      This issue was closed because it is a duplicate of {duplicateIssuesText}. That means someone else already requested this website to to be added as an extension before.

      *This is an automated action. If you think this is a mistake, please comment about it so the issue can be reopened if needed.*
  existing-check-enabled:
    required: false
    description: >
      Control if the action should search the extension repository for existing sources.
      Set it to 'true' if you want to enable.
  existing-check-label:
    required: false
    description: >
      The label of the opened issues that will be check.
      It's required if you have enabled the existing check.
  existing-check-repo-url:
    required: false
    description: >
      The URL of the JSON extensions repository.
      It's required if you have enabled the existing check.
    default: https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/index.min.json
  existing-check-comment:
    required: false
    description: >
      The body of the comment when an issue is detected to be of an existing source.
    default: |
      This issue was closed because an extension of this website already exists with the name of **{extensionName}**, under the **{extensionLang}** section.

      *This is an automated action. If you think this is a mistake, please comment about it so the issue can be reopened if needed.*
  auto-close-rules:
    required: false
    description: |
      A JSON-compliant string containing a list of rules, where a rule consists of:

      {
        type: 'title' | 'body' | 'both';  // Part to run regex against.
        regex: string;                    // Pattern which if matched closes the issue.
        message: string;                  // Message to post when closing the issue.
                                          // You can use {match} as a placeholder to the first match.
        ignoreCase: boolean | undefined;  // Defines if the regex will be case insensitive.
      }
  auto-close-ignore-label:
    required: false
    description: Optional label name. If present, auto-close rule execution is skipped.
runs:
  using: node16
  main: dist/index.js
